{{- if .Values.lmcache.redis.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.lmcache.redis.service.nameSuffix }}
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-lookup-server
spec:
  ports:
    - name: lookupserver-port
      protocol: TCP
      port: {{ .Values.lmcache.redis.service.port }}
      targetPort: {{ .Values.lmcache.redis.service.targetPort }}
  type: {{ .Values.lmcache.redis.service.type }}
  selector:
     {{- include "chart.redisSelectorLabels" . | nindent 4 }}
{{- end }}